#!/bin/bash
#SBATCH --job-name=t-cpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks=16
#SBATCH -p grafeno

module load openmpi/4.1.5-gcc-12.2.0-ptk6i3e
module load quantum-espresso/7.2-gcc-12.2.0-ohadjws

export OMP_NUM_THREADS=1

mpirun -np 16 pw.x -npool 1 -ndiag 1 -inp espresso.pwi >> espresso.pwo

