#!/bin/bash
#SBATCH --job-name=<job-cpu-name>
##SBATCH --nodes=1
#SBATCH --ntasks-per-node=<numero-de-cores>
#SBATCH --ntasks=<numero-de-cores>
#SBATCH -p <nome-da-fila>

module load openmpi/4.1.5-gcc-12.2.0-ptk6i3e
module load quantum-espresso/7.2-gcc-12.2.0-ohadjws

export OMP_NUM_THREADS=1

mpirun -np <numero-de-cores> pw.x -inp espresso.pwi >> espresso.pwo